module.exports.config={
  user:{
    header:'../partials/site/user/header',
    footer:'../partials/site/user/footer'
  },
  admin:{
    header:'../partials/site/admin/header',
    footer:'../partials/site/admin/footer'
  }
};